"""change columns and serialization

Revision ID: 8df35e8d7c33
Revises: 3f807c7c2ed0
Create Date: 2023-06-29 13:49:18.280524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df35e8d7c33'
down_revision = '3f807c7c2ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('for_sale')
        batch_op.drop_column('mileage')
        batch_op.drop_column('trim')

    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.drop_column('end_point')
        batch_op.drop_column('mileage')
        batch_op.drop_column('start_point')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_point', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('mileage', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('end_point', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trim', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('mileage', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('for_sale', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
